[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./builds/uniswap/"},
    { access = "read", path = "./test/the-rewarder/dvt-distribution.json"},
    { access = "read", path = "./test/the-rewarder/weth-distribution.json"},
    { access = "read", path = "./test/withdrawal/withdrawals.json"}
]
ignored_warnings_from = [
    "src/wallet-mining/TransparentProxy.sol",
    "lib/openzeppelin-contracts/contracts/proxy/Proxy.sol",
    "src/curvy-puppet/ICryptoSwapPool.sol"
]
bytecode_hash = "none"
remappings = [
    "forge-std/=lib/forge-std/src/", 
    "erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@uniswap/v2-core/=lib/v2-core/",
    "@uniswap/v2-periphery/=lib/v2-periphery/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@safe-global/safe-smart-account/=lib/safe-smart-account/",
    "murky/=lib/murky/src/",
    "safe-smart-account/=lib/safe-smart-account/",
    "solady/=lib/solady/src/",
    "solmate/=lib/solmate/src/",
    "permit2/=lib/permit2/src/"
    ]
